
<div class="container">
    <div class="box-login">
        <div class="account-wall">

            <img class="profile-img" src="<?= HTTP_IMG . '/logo.png' ?>" alt="PhpMyCall">

            <form class="form-signin" role="form" method="post" action="<?= HTTP . '/Login/efetuarLogin' ?>">

                <div class="row">
                    <div class="columns twelve">
                        <label class="columns four" for="usuario">Usuário:</label>
                        <input type="text" class="columns eight" name="usuario" placeholder="Usuário" required autofocus>
                    </div>
                </div>

                <div class="row">
                    <div class="columns twelve">
                        <label class="columns four" for="senha">Senha:</label>
                        <input type="password" class="columns eight" name="senha" placeholder="Senha" required>
                    </div>
                </div>

                <div class="row">
                    <button type="submit" class="button-secondary float-right">
                        Entrar
                    </button>
                </div>

        </div>

        </form>

    </div>
</div>
</div>
