
<?php
setlocale(LC_ALL, 'pt_BR.utf8');
header('Content-Type: text/html; charset=UTF-8');

use \application\controllers\Login, \libs\Cache, \libs\Menu;

?>


<html>
    <head>
        <meta charset="UTF-8">
        <title><?= $title ?></title>
        <link rel="stylesheet" href="<?= HTTP_CSS . '/bootstrap.min.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/bootstrap-theme.min.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.min.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.structure.min.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.theme.min.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/custom.css' ?>" />
        <script src="<?= HTTP_JS . '/jquery-1.11.2.min.js' ?>"></script>
        <script src="<?= HTTP_JS . '/jquery-ui.min.js' ?>"></script>
        <script src="<?= HTTP_JS . '/bootstrap.min.js' ?>"></script>
        <script type="text/javascript">
            (function ($) {
                $(document).ready(function () {
                    $('ul.dropdown-menu [data-toggle=dropdown]').on('click', function (event) {
                        event.preventDefault();
                        event.stopPropagation();
                        $(this).parent().siblings().removeClass('open');
                        $(this).parent().toggleClass('open');
                    });
                });
            })(jQuery);
        </script>
        <style rel="stylesheet" type="text/css">
            .marginBottom-0 {margin-bottom:0;}
            .dropdown-submenu{position:relative;}
            .dropdown-submenu>.dropdown-menu{top:0;left:100%;margin-top:-6px;margin-left:-1px;-webkit-border-radius:0 6px 6px 6px;-moz-border-radius:0 6px 6px 6px;border-radius:0 6px 6px 6px;}
            .dropdown-submenu>a:after{display:block;content:" ";float:right;width:0;height:0;border-color:transparent;border-style:solid;border-width:5px 0 5px 5px;border-left-color:#cccccc;margin-top:5px;margin-right:-10px;}
            .dropdown-submenu:hover>a:after{border-left-color:#555;}
            .dropdown-submenu.pull-left{float:none;}.dropdown-submenu.pull-left>.dropdown-menu{left:-100%;margin-left:10px;-webkit-border-radius:6px 0 6px 6px;-moz-border-radius:6px 0 6px 6px;border-radius:6px 0 6px 6px;}

        </style>
    </head>
    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">
                            myPhpHelpDesk
                        </span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">myPhpHelpDesk</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <?php if (Login::verificaLogin()) { ?>
                        <ul class="nav navbar-nav">

                            <?php
                            if (!($result = Cache::getCache("menu"))) {
                                $result = Menu::geraMenuPorPerfil();
                                Cache::setCache('menu', $result);
                            }

                            foreach ($result[$_SESSION['perfil']] as $nome_menu => $menu) {
                                if (is_array($menu)) {
                                    ?>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <?= $nome_menu ?> <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php
                                            foreach ($menu as $nome_submenu => $submenu) {
                                                if (is_array($submenu)) {
                                                    ?>
                                                    <li class="dropdown dropdown-submenu">
                                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                            <?= $nome_submenu ?>
                                                        </a>
                                                        <ul class="dropdown-menu">
                                                            <?php
                                                            foreach ($submenu as $nome_opcao => $opcao) {
                                                                ?>
                                                                <li>
                                                                    <a href="<?= HTTP . '/' . $opcao ?>"><?= $nome_opcao ?></a>
                                                                </li>
                                                                <?php
                                                            }
                                                            ?>
                                                        </ul>
                                                    </li>
                                                    <?php
                                                } else {
                                                    ?>
                                                    <li>
                                                        <a href="<?= HTTP . '/' . $submenu ?>"><?= $nome_submenu ?></a>
                                                    </li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li>
                                        <a href="<?= HTTP . '/' . $menu ?>"><?= $nome_menu ?></a>
                                    </li>
                                    <?php
                                }
                            }
                            ?>

                            <li>
                                <a href="<?= HTTP . "/Login/efetuarLogout" ?>">Logout</a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                <?php } ?>
            </div>
        </nav>