
<?php

use \application\controllers\Login,
    libs\Cache,
    libs\Menu;
?>


<html>
    <head>
        <meta charset="UTF-8">
        <title><?= $title ?></title>
        <link rel="stylesheet" href="<?= HTTP_CSS . '/normalize.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/skeleton.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.structure.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/jquery-ui.theme.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/custom.css' ?>" />
        <link rel="stylesheet" href="<?= HTTP_CSS . '/aguarde.css' ?>" />

        <script type="text/javascript" src="<?= HTTP_JS . '/jquery-1.11.2.min.js' ?>"></script>
        <script type="text/javascript" src="<?= HTTP_JS . '/jquery-ui.min.js' ?>"></script>
        <script type="text/javascript" src="<?= HTTP_JS . '/aguarde.js' ?>"></script>
    </head>
    <body>

        <header class="block">
            <nav id="header_page">

                <div id="nav_header">PhpMyCall</div>

                <div id="menus">
                    <?php if (Login::verificaLogin()) { ?>
                        <ul>

                            <?php
                            if (!($result = Cache::getCache("menu"))) {
                                $result = Menu::geraMenuPorPerfil();
                                Cache::setCache('menu', $result);
                            }

                            foreach ($result [$_SESSION ['perfil']] as $nome_menu => $menu) {
                                if (is_array($menu)) {
                                    ?>
                                    <li>
                                        <a href="#">
                                            <?= $nome_menu ?>
                                        </a>
                                        <ul>
                                            <?php
                                            foreach ($menu as $nome_submenu => $submenu) {
                                                if (is_array($submenu)) {
                                                    ?>
                                                    <li>
                                                        <a href="#">
                                                            <?= $nome_submenu ?> <span class="caret-right"></span>
                                                        </a>
                                                        <ul>
                                                            <?php
                                                            foreach ($submenu as $nome_opcao => $opcao) {
                                                                ?>
                                                                <li>
                                                                    <a href="<?= HTTP . '/' . $opcao ?>"><?= $nome_opcao ?></a>
                                                                </li>
                                                                <?php
                                                            }
                                                            ?>
                                                        </ul>
                                                    </li>
                                                    <?php
                                                } else {
                                                    ?>
                                                    <li>
                                                        <a href="<?= HTTP . '/' . $submenu ?>"><?= $nome_submenu ?></a>
                                                    </li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <?php
                                } else {
                                    ?>
                                    <li>
                                        <a href="<?= HTTP . '/' . $menu ?>"><?= $nome_menu ?></a>
                                    </li>
                                    <?php
                                }
                            }
                            ?>

                            <li>
                                <a href="<?= HTTP . "/Login/efetuarLogout" ?>">Logout</a>
                            </li>
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                <?php } ?>
            </nav>
        </header>

        <div class="block push">
            <div class="container">