

<script type="text/javascript">

    $(document).ready(function () {

        $('#alterar-projeto').dialog({
            autoOpen: true,
            modal: true,
            width: 500,
            buttons: {
                "Cancelar": function () {
                    $('#alterar-projeto').dialog('close');
                }
            }
        });

        $('#accordion').accordion();

        $("button[name='enviar-form']").click(function (event) {

            var id = $("input[name='inputID']").val();

            $.ajax({
                url: '<?= HTTP . '/ProjetosProblemas/relacaoUsuarios'; ?>',
                type: 'POST',
                data: 'id=' + id,
                success: function (data) {
                    $('#participantes').html(data);
                }
            });
        });

        $("a[projeto]").click(function (event) {
            event.preventDefault();
            $('#inputProjetoProblema').val($(this).attr('projeto'));

            $.ajax({
                url: '<?= HTTP . '/ProjetosProblemas/getDadosProjetosProblemas' ?>',
                type: 'POST',
                data: 'id=' + $(this).attr('projeto'),
                dataType: 'json',
                success: function (data) {
                    $('#inputID').val(data.id);
                    $('#inputProjetoOld').val(data.id);
                    $('#inputProjeto').val(data.projeto);
                    $('#inputProblema').val(data.problema);
                    $('#inputResposta').val(data.resposta);
                    $('#inputSolucao').val(data.solucao);
                    $('#textDescricao').val(data.descricao);
                    $('#alterar-projeto').dialog('close');
                }
            });
        });

    });

</script>

<div id="alterar-projeto" title="Selecione um projeto">
    <div id="accordion">
        <?php foreach ($listaProjeto as $nome_projeto => $projeto) { ?>
            <h3>
                <?= $nome_projeto ?>
            </h3>
            <div>
                <?php foreach ($projeto as $key => $values) { ?>
                    <a href="#" class="btn btn-link" projeto="<?= $key ?>"><?= $values ?></a><br/>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>