
<script type="text/javascript">
    $(document).ready(function () {
        $("input[name='inputProjeto']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/ProjetosProblemas/getProjetos' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            }
        });

        $("input[name='inputProblema']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/ProjetosProblemas/getProblemas' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            }
        });

    });
</script>

<div class="container">
	<form class="form-horizontal">
		<div class="form-group">
			<label for="inputProjeto" class="control-label col-xs-2">Projeto</label>
			<div class="col-xs-10">
				<input type="text" class="form-control" id="inputProjeto"
					name="inputProjeto" placeholder="Projeto">
			</div>
		</div>

		<div class="form-group">
			<label for="inputProblema" class="control-label col-xs-2">Tipo de
				Problema</label>
			<div class="col-xs-10">
				<input type="text" class="form-control" id="inputProblema"
					name="inputProblema" placeholder="Tipo de problema">
			</div>
		</div>

		<div class="form-group">
			<label for="inputResposta" class="control-label col-xs-2">Tempo de
				resposta</label>
			<div class="col-xs-10">
				<input type="text" class="form-control" id="inputResposta"
					name="inputResposta" placeholder="Tempo de resposta">
			</div>
		</div>

		<div class="form-group">
			<label for="inputSolucao" class="control-label col-xs-2">Tempo para
				solução</label>
			<div class="col-xs-10">
				<input type="text" class="form-control" id="inputSolucao"
					placeholder="Tempo para solução">
			</div>
		</div>


		<div class="form-group">
			<label for="textDescricao" class="control-label col-xs-2">Descrição</label>
			<div class="col-xs-10">
				<textarea class="form-control" id="textDescricao"
					placeholder="Descrição do projeto"></textarea>
			</div>
		</div>

		<div class="form-group">
			<div class="col-xs-offset-2 col-xs-10">
				<button type="submit" class="btn btn-primary">Login</button>
			</div>
		</div>
	</form>
</div>