

<script type="text/javascript"
	src="<?= HTTP_JS . '/bootstrap-transfer.js' ?>"></script>

<script type="text/javascript">

	$(document).ready(function(){
		$("form").on('submit', function(event){

			var id = $("input[name='inputID']").val();

			if(id == 0){
				event.preventDefault();
				
				$.ajax({
					url: '<?= HTTP . '/ProjetosProblemas/relacaoUsuarios'; ?>',
					type: 'POST',
					success: function(data){
						$('#participantes').html(data);
						$('#participantes').modal({
			                backdrop: 'static',
			                keyboard: false
			            });
					}
				});
			}
		});
	});

</script>

