<script type="text/javascript"
src="<?= HTTP_JS . '/jquery.select-filter.min.js' ?>"></script>

<script type="text/javascript">

    $(document).ready(function () {

        $('#excluir-projeto').dialog({
            autoOpen: true,
            modal: true,
            width: 500,
            buttons: {
                "Cancelar": function () {
                    $('#excluir-projeto').dialog('close');
                }
            }
        });

        $('#accordion').accordion();

        var excluir_projeto = $('#confirmar-excluir-projeto').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "Excluir": function () {
                    $("form[name='projeto-problemas']").submit();
                },
                "Cancelar": function () {
                    excluir_projeto.dialog('close');
                }
            }
        });

        $("button[name='enviar-form']").click(function (event) {
            excluir_projeto.dialog('open');
        });

        $('input').attr('readonly', true);
        $('textarea').attr('readonly', true);

        $("a[projeto]").click(function (event) {
            event.preventDefault();
            $('#inputProjetoProblema').val($(this).attr('projeto'));

            $.ajax({
                url: '<?= HTTP . '/ProjetosProblemas/getDadosProjetosProblemas' ?>',
                type: 'POST',
                data: 'id=' + $(this).attr('projeto'),
                dataType: 'json',
                success: function (data) {
                    $('#inputID').val(data.id);
                    $('#inputProjetoOld').val(data.id);
                    $('#inputProjeto').val(data.projeto);
                    $('#inputProblema').val(data.problema);
                    $('#inputResposta').val(data.resposta);
                    $('#inputSolucao').val(data.solucao);
                    $('#textDescricao').val(data.descricao);
                    $('#excluir-projeto').dialog('close');
                }
            });
        });

    });

</script>

<div id="excluir-projeto" title="Selecione um projeto">
    <div id="accordion">
        <?php foreach ($listaProjeto as $nome_projeto => $projeto) { ?>
            <h3>
                <?= $nome_projeto ?>
            </h3>
            <div>
                <?php foreach ($projeto as $key => $values) { ?>
                    <a href="#" class="btn btn-link" projeto="<?= $key ?>"><?= $values ?></a><br/>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>



<div id="confirmar-excluir-projeto" title="Atenção">
    <p class="text-center">Deseja realmente excluir este tipo de problema para este projeto?</p>
</div>