

<script type="text/javascript">
    $(document).ready(function () {

        $("input[name='inputProjeto']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/ProjetosProblemas/getProjetos' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            }
        }).on('focusout', function () {
            $.ajax({
                url: '<?= HTTP . '/ProjetosProblemas/getDadosProjeto' ?>',
                data: 'nome=' + $(this).val(),
                dataType: 'json',
                type: 'post',
                success: function (data) {
                    multi.setOrigin(data.usuarios);
                    multi.setDestiny(data.participantes);
                }
            });
        });

        $("input[name='inputProblema']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/ProjetosProblemas/getProblemas' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            }
        });

        $('#inputResposta, #inputSolucao').mask('0HHH:M0', {
            translation: {
                'H': {pattern: /[0-9]/, optional: true},
                'M': {pattern: /[0-5]/}
            }
        }).attr('pattern', '[0-9]{1,4}:[0-5][0-9]');

        var dialog = $('#dialogProjetosProblemas').dialog({
            autoOpen: false,
            closeOnEscape: false,
            modal: true,
            width: '80%',
            buttons: [
                {
                    text: 'Salvar',
                    icons: {
                        primary: 'ui-icon-disk'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ]
        });

        $('#projetoProblemas').tabs();

    });
</script>


<div id="dialogProjetosProblemas">
    <form name="projetoProblemas" id="projetoProblemas">

        <ul>
            <li><a href="#cadastroProjeto">Projeto tipo problema</a></li>
            <li><a href="#usuariosProjeto">Participantes</a></li>
        </ul>

        <div id="cadastroProjeto">
            <input type="hidden" name="inputID" id="inputID" value="0" />
            <input type="hidden" name="inputProblema" id="inputProblema" value="0" />
            <input type="hidden" name="inputProjetoProblema" id="inputProjetoProblema" value="0" />

            <fieldset>
                <legend>Projeto</legend>
                <div class="row">
                    <label for="inputProjeto" class="columns four">Nome do projeto:</label>
                    <input type="text" class="columns eight" id="inputProjeto" name="inputProjeto" placeholder="Projeto" maxlength="100">
                </div>

                <div class="row">
                    <label for="textProjeto" class="columns four">Descrição do projeto (Opcional):</label>
                    <textarea class="columns eight" id="textProjeto" name="textProjeto" placeholder="Descrição do projeto" maxlength="500"></textarea>
                </div>
            </fieldset>

            <fieldset>
                <legend>Problema</legend>
                <div class="row">
                    <label for="inputProblema" class="columns four">Tipo de Problema:</label>
                    <input type="text" class="columns eight" id="inputProblema" name="inputProblema" placeholder="Tipo de problema" maxlength="100">
                </div>

                <div class="row">
                    <label for="textDescricao" class="columns four">Descrição do tipo de problemas:</label>
                    <textarea id="textDescricao" class="columns eight" maxlength="1000" name="textDescricao" placeholder="Descrição do tipo de problema"></textarea>
                </div>
            </fieldset>

            <fieldset>
                <legend>Prazos</legend>
                <div class="row">
                    <label for="inputResposta" class="columns two">Resposta:</label>
                    <input type="text" class="columns four" id="inputResposta" name="inputResposta" placeholder="Tempo de resposta">

                    <label for="inputSolucao" class="columns two">Solução:</label>
                    <input type="text" class="columns four" id="inputSolucao" name="inputSolucao" placeholder="Tempo para solução">
                </div>
            </fieldset>
        </div>

        <div id="usuariosProjeto">
            <div id="relacaoUsuarios"></div>
        </div>

    </form>
</div>