
<link href="<?= HTTP_CSS . '/multi-select-transfer.css' ?>" rel="stylesheet" />
<script type="text/javascript" src="<?= HTTP_JS . '/multi-select-transfer.js' ?>"></script>
<script type="text/javascript" src="<?= HTTP_JS . '/jquery.mask.min.js' ?>"></script>

<script type="text/javascript">

    /*
     * Instancia objeto para exiber mensagem de aguarde.
     */
    var aguarde = new Aguarde('<?= HTTP_IMG . '/change.gif' ?>');

    $(document).ready(function () {

        multi = new MultiSelectTransfer('#relacaoUsuarios', {name_select_destiny: 'participantes'});
        multi.init();

        /*
         * Gera botão de cadastrar usuário e ação de clica-lo
         */
        $('button[type=button][name=cadastrar]').button({
            icons: {
                primary: 'ui-icon-circle-plus'
            }
        }).on('click', function () {
            aguarde.mostrar();

            multi.setOrigin();
            multi.setDestiny();

            $('input').val('');
            $('input[type=hidden]').val(0);

            $('#dialogProjetosProblemas').dialog('option', 'title', 'Cadastrar projeto tipo de problema');
            $('#dialogProjetosProblemas + div.ui-dialog-buttonpane > div.ui-dialog-buttonset > button:first-child > span.ui-button-text').html('Cadastrar');
            $('#dialogProjetosProblemas').dialog('open');

            aguarde.ocultar();
        });

        $('#alert_dialog').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "OK": function () {
                    $('#alert_dialog').dialog('close');
                }
            }
        });

    });
</script>

<div class="container">

    <div class="row">
        <div id="msg-status" class="alert hide text-center"></div>
    </div>

    <div class="row">
        <button type="button" name="cadastrar" id="cadastrar">Cadastrar</button>
    </div>

    <div id="relacaoProjetoProblemas"></div>

</div>

<div id="alert_dialog" title="Aviso">
    <p id="alert_dialog_msg"></p>
</div>
