
<div class="modal-dialog" style="width: 80%;">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"
				aria-hidden="true">&times;</button>
			<h4 class="modal-title">Adicionar Participantes</h4>
		</div>

		<div class="modal-body" id="relacao_usuarios"></div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
			<button type="button" class="btn btn-success">Salvar</button>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function () {
		var t = $('#relacao_usuarios').bootstrapTransfer({
			'target_id': 'multi-select-input',
			'height': '15em',
			'hilite_selection': true
		});

		t.populate([
<?php
foreach ( $usuarios as $values ) {
	?>
		{value: "<?= $values['id'] ?>", content: "<?= "{$values['nome']} - {$values['perfil']}" ?>"},
<?php } ?>
		]);
	});
</script>
