
<script type="text/javascript">
    $(document).ready(function () {

        //url: '/Feedback/getDadosTipoFeedback';

        $('#dialogFeedback').dialog({
            autoOpen: false,
            closeOnEscape: false,
            modal: true,
            width: '80%',
            height: $(window).height() * 0.95,
            buttons: [
                {
                    text: 'Salvar',
                    icons: {
                        primary: 'ui-icon-disk'
                    },
                    click: function () {
                        feedback.submitFormulario();
                        $(this).dialog('close');
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ],
            position: {my: 'center', at: 'center', of: window}
        });

    });
</script>

<div id="dialogFeedback">
    <form name="formulario">
        <input type="hidden" name="inputID" id="inputID" value="0" />

        <div class="row">
            <label for="inputNome" class="four columns">Nome</label>
            <input type="text" class="eight columns" id="inputNome" name="inputNome" placeholder="Nome" maxlenght="50">
        </div>

        <div class="row">
            <label for="inputAbreviatura" class="four columns">Abreviatura</label>
            <input type="text" class="four columns" id="inputAbreviatura" required name="inputAbreviatura" placeholder="Abreviatura" maxlenght="10">
            <label for="inputDescontar" class="four columns">
                <input type="checkbox" name="inputDescontar" id="inputDescontar" />
                Descontar do tempo total de solução?
            </label>
        </div>

        <div class="row">
            <label for="textDescricao" class="four columns">Descrição</label>
            <textarea class="twelve columns" id="textDescricao" maxlength="1000" name="textDescricao" placeholder="Descrição do feedback"></textarea>
        </div>
    </form>
</div>