
<script type="text/javascript">

    /*
     * Instancia objeto para exiber mensagem de aguarde.
     */
    var aguarde = new Aguarde('<?= HTTP_IMG . '/change.gif' ?>');

    var Feedback = function () {

        var formulario = ''; // cadastrar ou alterar
        var feedback = 0;

        /**
         * Seta formulario para cadastro
         */
        this.setCadastrar = function () {
            formulario = 'cadastrar';
        };

        /**
         * Seta formulario de alteração
         */
        this.setAlterar = function () {
            formulario = 'alterar';
        };

        /**
         * Seta dados para solicitar posterior exclusão
         * @param {int} id_feedback Código do feedback
         */
        this.setExcluir = function (id_feedback) {
            feedback = id_feedback;
        };

        /**
         * Envia formulario para cadastro ou alteração
         */
        this.submitFormulario = function () {
            aguarde.mostrar();

            $.ajax({
                url: '<?= HTTP . '/Feedback/' ?>' + formulario,
                data: $('form[name=formulario]').serialize(),
                dataType: 'JSON',
                type: 'POST',
                async: false,
                success: function (data) {

                    if (data.status) {
                        $('#msg-status').removeClass('hide alert-danger').addClass('alert-success');
                        $('#msg-status').html(data.msg);
                    } else {
                        $('#msg-status').removeClass('hide alert-success').addClass('alert-danger');
                        $('#msg-status').html(data.msg);
                    }

                    geraTabelaFeedback(data.feedback);
                }
            });

            aguarde.ocultar();
        };

        /*
         * Gera tabela com tipo de feedback's
         * @param {json} data Objeto json com os tipo de feedback
         */
        var geraTabelaFeedback = function (data) {
            var table = '<table class="u-full-width">';
            table += '<thead>';
            table += '<tr>';
            table += '<th class="col3">Nome</th>';
            table += '<th class="col2">Abreviatura</th>';
            table += '<th class="col1">Descontar tempo total</th>';
            table += '<th class="col4">Descrição</th>';
            table += '<th class="col2"></th>';
            table += '</tr>';
            table += '</thead>';
            table += '<tbody>';

            $.each(data, function (key, value) {
                table += '<tr>';
                table += '<td>' + value.nome + '</td>';
                table += '<td>' + value.abreviatura + '</td>';
                table += '<td>' + (value.descontar ? 'Sim' : 'Não') + '</td>';
                table += '<td>' + value.descricao + '</td>';
                table += '<td class="text-center">';
                table += '<button type="button" name="editar" feedback="' + value.id + '">Editar</button>';
                table += '<button type="button" name="excluir" feedback="' + value.id + '">Excluir</button>';
                table += '</td>';
                table += '</tr>';
            });

            table += '</tbody>';
            table += '</table>';

            $('#tabelaFeedbacks').html(table);

            ButtonEditar();
            ButtonExcluir();
        };

        /*
         * Solicita a exclusão do projeto
         */
        this.excluir = function () {
            aguarde.mostrar();

            $.ajax({
                url: '<?= HTTP . '/Feedback/excluir' ?>',
                data: 'id=' + feedback,
                dataType: 'json',
                type: 'post',
                async: false,
                success: function (data) {

                    if (data.status) {
                        $('#msg-status').removeClass('hide alert-danger').addClass('alert-success');
                        $('#msg-status').html(data.msg);
                    } else {
                        $('#msg-status').removeClass('hide alert-success').addClass('alert-danger');
                        $('#msg-status').html(data.msg);
                    }

                    geraTabelaFeedback(data.feedback);
                }
            });

            aguarde.ocultar();
        };
    };

    feedback = new Feedback();


    /*
     * Gera botão para edição de feedback
     */
    var ButtonEditar = function () {

        $('button[name=editar]').button({
            text: false,
            icons: {
                primary: 'ui-icon-pencil'
            }
        }).on('click', function () {
            aguarde.mostrar();

            feedback.setAlterar();

            var id = $(this).attr('feedback');

            $.ajax({
                url: '<?= HTTP . '/Feedback/getFeedback' ?>',
                data: 'feedback=' + id,
                dataType: 'json',
                type: 'post',
                async: false,
                success: function (data) {
                    $('#inputID').val(data.id);
                    $('#inputNome').val(data.nome);
                    $('#inputAbreviatura').val(data.abreviatura);
                    $('#inputDescontar').prop('checked', data.descontar === true);
                    $('#textDescricao').val(data.descricao);
                }
            });

            $('#dialogFeedback').dialog('option', 'title', 'Alterar tipo de feedback');
            $('#dialogFeedback + div.ui-dialog-buttonpane > div.ui-dialog-buttonset > button:first-child > span.ui-button-text').html('Alterar');
            $('#dialogFeedback').dialog('open');

            aguarde.ocultar();
        });

    };

    /*
     * Cria botão de exclusão e adiciona evento ao clica-lo
     */
    var ButtonExcluir = function () {

        $('button[name=excluir]').button({
            text: false,
            icons: {
                primary: 'ui-icon-close'
            }
        }).on('click', function () {
            $('#alertaExclusao').dialog('open');
            feedback.setExcluir($(this).attr('feedback'));
        });

    };


    $(document).ready(function () {

        ButtonEditar();
        ButtonExcluir();

        /*
         * Gera botão de cadastrar usuário e ação de clica-lo
         */
        $('button[type=button][name=cadastrar]').button({
            icons: {
                primary: 'ui-icon-circle-plus'
            }
        }).on('click', function () {
            aguarde.mostrar();
            feedback.setCadastrar();

            $('input, textarea').val('');
            $('input[type=hidden]').val(0);

            $('#dialogFeedback').dialog('option', 'title', 'Cadastrar tipo de feedback');
            $('#dialogFeedback + div.ui-dialog-buttonpane > div.ui-dialog-buttonset > button:first-child > span.ui-button-text').html('Cadastrar');
            $('#dialogFeedback').dialog('open');

            aguarde.ocultar();
        });

        /*
         * dialog solicitando confirmação para exclusão.
         */
        $('#alertaExclusao').dialog({
            autoOpen: false,
            modal: true,
            closeOnEscape: false,
            buttons: [
                {
                    text: 'Excluir',
                    icons: {
                        primary: 'ui-icon-trash'
                    },
                    click: function () {
                        feedback.excluir();
                        $(this).dialog('close');
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ]
        });

    });

</script>

<div class="container">

    <div class="row">
        <div id="msg-status" class="alert hide text-center"></div>
    </div>

    <div class="row">
        <button type="button" name="cadastrar" id="cadastrar">Cadastrar</button>
    </div>

    <div id="tabelaFeedbacks">

        <table class="u-full-width">
            <thead>
                <tr>
                    <th class="col3">Nome</th>
                    <th class="col2">Abreviatura</th>
                    <th class="col1">Descontar tempo total</th>
                    <th class="col4">Descrição</th>
                    <th class="col2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($feedback as $values) { ?>
                    <tr>
                        <td><?= $values['nome'] ?></td>
                        <td><?= $values['abreviatura'] ?></td>
                        <td><?= $values['descontar'] ? 'Sim' : 'Não' ?></td>
                        <td><?= nl2br($values['descricao']) ?></td>
                        <td class="text-center">
                            <button type="button" name="editar" feedback="<?= $values['id'] ?>">Editar</button>
                            <button type="button" name="excluir" feedback="<?= $values['id'] ?>">Excluir</button>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<div id="alertaExclusao" title="Alerta de remoção">
    <p class="ui-state-error-text">
        Deseja realmente remover este tipo de feedback?
    </p>
</div>