
<script type="text/javascript">

	$(document).ready(function(){
		$("#add-projetos").modal({
			backdrop: 'static',
            keyboard: false
		});

		$("#confirma").on('click', function(){
			$('form').submit();
		});
	});

</script>

<div id="add-projetos" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title">Selecione os projetos que o usuário irá
					participar?</h4>
			</div>

			<div class="modal-body">

				<div class="form-horizontal">
				<?php
				foreach ( $projetos as $values ) {
					?>
					<div class="form-group">
						<label for="projeto<?= $values['id']; ?>"
							class="control-label col-xs-12 text-right"> <input
							type="checkbox" name="projeto[]" id="projeto<?= $values['id']?>"
							value="<?= $values['id']?>"
							<?php if($values['participante'] == 1){echo "checked";} ?> /> <?= $values['nome'];?>
						</label>
					</div>
					<?php
				}
				?>
				</div>

			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-success" id="confirma">Adicionar</button>
			</div>
		</div>
	</div>
</div>