
<script type="text/javascript">
    $(document).ready(function () {

        $("input[name='inputUsuario']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getUsuarioNome' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            },
            select: function (event, json) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getDadosUsuarios'; ?>',
                    data: 'usuario=' + json.item.value,
                    dataType: 'json',
                    type: 'POST',
                    success: function (json) {
                        $('#inputID').val(json.id);
                        $('#inputNome').val(json.nome);
                        $('#inputUsuario').val(json.usuario);
                        $('#inputEMail').val(json.email);
                        $('#inputTelefone').val(json.telefone);
                        $('#selectPerfil').val(json.perfil);
                        $('#selectEmpresa').val(json.empresa);
                        $('#selectPerfil').change();
                    }
                });
                $('#inputNome').prop('disabled', false);
                $('#inputEMail').prop('disabled', false);
                $('#selectPerfil').prop('disabled', false);
                $('#inputSenha').prop('disabled', false);
                $('#inputTelefone').prop('disabled', false);
                $('#selectEmpresa').prop('disabled', false);
            }
        });

        $('#inputNome').prop('disabled', true);
        $('#inputEMail').prop('disabled', true);
        $('#selectPerfil').prop('disabled', true);
        $('#inputSenha').prop('disabled', true);
        $('#inputSenha').prop('required', false);
        $('#inputTelefone').prop('disabled', true);
        $('#selectEmpresa').prop('disabled', true);

    });
</script>