
<script type="text/javascript">
    $(document).ready(function () {

        $("input[name='inputUsuario']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getUsuarioNome' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            },
            select: function (event, json) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getDadosUsuarios'; ?>',
                    data: 'usuario=' + json.item.value,
                    dataType: 'json',
                    type: 'POST',
                    success: function (json) {
                        $('#inputID').val(json.id);
                        $('#inputNome').val(json.nome);
                        $('#inputUsuario').val(json.usuario);
                        $('#inputEMail').val(json.email);
                        $('#inputTelefone').val(json.telefone);
                        $('#selectPerfil').val(json.perfil);
                        $('#selectEmpresa').val(json.empresa);
                        $('#selectPerfil').change();
                    }
                });
                $('#inputNome').attr('readonly', false);
                $('#inputEMail').attr('readonly', false);
                $('#selectPerfil').attr('readonly', false);
                $('#inputSenha').attr('readonly', false);
                $('#inputTelefone').attr('readonly', false);
                $('#selectEmpresa').attr('readonly', false);
            }
        });

        $('#inputNome').attr('readonly', true);
        $('#inputEMail').attr('readonly', true);
        $('#selectPerfil').attr('readonly', true);
        $('#inputSenha').attr('readonly', true);
        $('#inputSenha').attr('required', false);
        $('#inputTelefone').attr('readonly', true);
        $('#selectEmpresa').attr('readonly', true);

        $("button[name='submit-dados']").on('click', function () {
            $.ajax({
                url: '<?= HTTP . '/Usuarios/getProjetos' ?>',
                type: 'POST',
                data: 'id=' + $('#inputID').val(),
                success: function (dados) {
                    $("#modal-projetos").html(dados);
                }
            });
        });

    });
</script>