<script type="text/javascript">
    $(document).ready(function () {

        $("button[name='submit-dados'][type='button']").on('click', function () {
            $.ajax({
                url: '<?= HTTP . '/Usuarios/getProjetos' ?>',
                type: 'POST',
                data: 'id=' + $('#inputID').val(),
                success: function (dados) {
                    $("#modal-projetos").html(dados);
                }
            });
        });

    });
</script>