
<script type="text/javascript">
    $(document).ready(function () {

        $("input[name='inputUsuario']").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getUsuarioNome' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
                });
            },
            focus: function (event, json) {
                $.ajax({
                    url: '<?= HTTP . '/Usuarios/getDadosUsuarios'; ?>',
                    data: 'usuario=' + json.item.value,
                    dataType: 'json',
                    type: 'POST',
                    success: function (json) {
                        $('#inputID').val(json.id);
                        $('#inputNome').val(json.nome);
                        $('#inputUsuario').val(json.usuario);
                        $('#inputEMail').val(json.email);
                        $('#inputTelefone').val(json.telefone);
                        $('#selectPerfil').val(json.perfil);
                        $('#selectPerfil').change();
                        $('#selectEmpresa').val(json.empresa);
                    }
                });
            }
        });

        $('#inputNome').prop('disabled', true);
        $('#inputEMail').prop('disabled', true);
        $('#selectPerfil').prop('disabled', true);
        $('#inputSenha').prop('disabled', true);
        $('#inputSenha').prop('required', false);
        $('#inputChangeme').prop('disabled', true);
        $('#inputTelefone').prop('disabled', true);
        $('#selectEmpresa').prop('disabled', true);

        $('#confirmar-exclusao').dialog({
            autoOpen: false,
            modal: true,
            closeOnEscape: false,
            width: '25%',
            buttons: [
                {
                    text: 'Excluir',
                    icons: {
                        primary: 'ui-icon-trash'
                    },
                    click: function () {
                        $(this).dialog('close');
                        // cancela o disabled para poder ser enviado
                        $('#inputEMail').prop('disabled', false);
                        $('form[name=formUsuario]').submit();
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ]
        });

        $("button[name='submit-dados']").on('click', function () {

            $('#confirmar-exclusao').dialog('open');
        });

        $('#confirmar-exclusao').removeClass('hide');
    });
</script>

<div id="confirmar-exclusao" class="hide" type="Atenção">
    <div>
        <p class="text-center">Deseja excluir este usuário?</p>
    </div>
</div>