
<script type="text/javascript">
	$(document).ready(function(){

		$("input[name='inputUsuario']").autocomplete({
			source: function (request, response) {
				$.ajax({
					url: '<?= HTTP . '/Usuarios/getUsuarioNome' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
				});
			},
			focus: function(event, json){
				$.ajax({
					url: '<?= HTTP . '/Usuarios/getDadosUsuarios'; ?>',
					data: 'usuario=' + json.item.value,
					dataType: 'json',
					type: 'POST',
					success: function(json){
						$('#inputID').val(json.id);
						$('#inputNome').val(json.nome);
						$('#inputUsuario').val(json.usuario);
						$('#inputEMail').val(json.email);
						$('#selectPerfil').val(json.perfil);
					}
				});
			}
		});

		$('#inputNome').attr('readonly', true);
		$('#inputEMail').attr('readonly', true);
		$('#selectPerfil').attr('disabled', true);
		$('#inputSenha').attr('readonly', true);
		$('#inputSenha').attr('required', false);
		$('#inputChangeme').attr('disabled', true);

		$("button[name='submit-dados']").on('click', function (){

			$('#confirmar-exclusao').modal({
				backdrop: 'static',
	            keyboard: false
			});
		});

		$('#confirma-exclusao').on('click', function(){
			$('form').submit();
		});
		
	});
</script>

<div id="confirmar-exclusao" class="modal fade">
	<div class="modal-dialog" style="width: 80%;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title">Atenção</h4>
			</div>

			<div class="modal-body">
				<p class="text-center">Deseja excluir este usuário?</p>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-danger" id="confirma-exclusao">Excluir</button>
			</div>
		</div>
	</div>
</div>