
<script type="text/javascript" src="<?= HTTP_JS . '/multi-select-transfer.js' ?>"></script>
<link href="<?= HTTP_CSS . '/multi-select-transfer.css' ?>" rel="stylesheet" />

<script type="text/javascript">

    $(document).ready(function () {

        $('button[type=button][name=cadastrar]').button({
            icons: {
                primary: 'ui-icon-circle-plus'
            }
        }).on('click', function () {

            $.ajax({
                url: '<?= HTTP . '/Usuarios/getProjetos' ?>',
            });

            $('#formulario_cadastro').dialog('option', 'title', 'Cadastrar usuário');
            $('#formulario_cadastro').dialog('open');
        });

    });

</script>

<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> text-center">
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <div class="row">
        <button type="button" name="cadastrar" id="cadastrar">Cadastrar</button>
    </div>

</div>