
<script type="text/javascript">
    $(document).ready(function () {

        $('#projeto_participante').dialog({
            autoOpen: false,
            modal: true,
            closeOnEscape: false,
            width: 450,
            buttons: [
                {
                    text: 'Adicionar',
                    icons: {
                        primary: 'ui-icon-circle-plus'
                    },
                    click: function () {
                        var value = '';

                        $('input[type=checkbox][name=projeto]:checked').each(function () {
                            value += (value === '' ? '' : ',') + $(this).val();
                        });

                        $('input[name=inputProjetos]').val(value);
                        $('#formUsuario').submit();
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-circle-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ]
        });

        $("button[name='submit-dados'][type='button']").on('click', function () {
            $.ajax({
                url: '<?= HTTP . '/Usuarios/getProjetos' ?>',
                type: 'POST',
                dataType: 'JSON',
                data: 'id=' + $('#inputID').val(),
                success: function (dados) {
                    var checkbox = '';

                    $.each(dados, function (key, value) {
                        checkbox += '<div class="row">';
                        checkbox += '<label for="projeto' + value.id + '" class="twelve columns">';
                        checkbox += '<input type="checkbox" name="projeto" id="projeto' + value.id + '" value="' + value.id + '" ' + (value.participante == 1 ? "checked" : '') + '/>';
                        checkbox += '<span style="margin-left: 5%;">';
                        checkbox += value.nome;
                        checkbox += '</span>';
                        checkbox += '</label>';
                        checkbox += '</div>';
                    });

                    $('#projetos').html(checkbox);
                    $('#projeto_participante').dialog('open');

                }
            });
        });

        $('#projeto_participante').removeClass('hide');
    });
</script>

<div id="projeto_participante" class="hide" title="Selecione os projetos que o usuário irá participar?">
    <div id="projetos"></div>
</div>
