
<script type="text/javascript">
	$(document).ready(function(){

		$("input[name='inputNome']").autocomplete({
			source: function (request, response) {
				$.ajax({
					url: '<?= HTTP . '/Usuarios/get_usuario_nome' ?>',
                    data: request,
                    dataType: 'json',
                    type: 'POST',
                    success: function (data) {
                        response(data);
                    }
				});
			},
			select: function(event, ui){
				alert(ui.item.label + ' ' + ui.item.value);
			}
		});

		$('#inputSenha').attr('required', false);
		
		$('#editar_usuario').on('click', function(){
			var nome = $("input[name='nome']").val();
			var usuario = $("input[name='usuario']").val();
			
			if(id.length > 0){
				$.ajax({
					url: '<?= HTTP . '/Usuarios/get_dados_usuarios'; ?>',
					data: 'id=' + id,
					dataType: 'json',
					type: 'POST',
					success: function(json){
						$('#inputID').val(json.id);
						$('#inputNome').val(json.nome);
						$('#inputUsuario').val(json.usuario);
						$('#inputEMail').val(json.email);
						$('#selectPerfil').val(json.perfil);
						$('#inputSenha').attr('required', false);
					}
				});
			}
		});
		
	});
</script>