

<script type="text/javascript">
    $(document).ready(function () {

        $('tbody > tr').click(function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/visualizar" ?>/' + $(this).attr('solicitacao'));
        });

    });
</script>


<div class="container">

    <div class="panel-group" id="accordion">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"> Solicitações em aberto </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">

                    <table class="table table-responsive table-bordered table-solicitacoes">
                        <thead>
                            <tr>
                                <th>Projeto</th>
                                <th>Problema</th>
                                <th>Prioridade</th>
                                <th>Solicitante</th>
                                <th>Atendente</th>
                                <th>Abertura</th>
                                <th>Quant. Arquivos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($aberta as $values) {
                                ?>
                                <tr style="background-color: <?= $prioridades[$values['prioridade']] ?>" solicitacao="<?= $values['solicitacao']; ?>">
                                    <td>
                                        <?= $values['projeto'] ?>
                                    </td>
                                    <td>
                                        <?= $values['problema'] ?>
                                    </td>
                                    <td>
                                        <?= $values['prioridade'] ?>
                                    </td>
                                    <td>
                                        <?= $values['solicitante'] ?>
                                    </td>
                                    <td>
                                        <?= $values['atendente'] ?>
                                    </td>
                                    <td>
                                        <?= $values['abertura'] ?>
                                    </td>
                                    <td>
                                        <?= $values['arquivos'] ?>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"> Solicitações em atendimento </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">

                    <table class="table table-responsive table-bordered table-solicitacoes">
                        <thead>
                            <tr>
                                <th>Projeto</th>
                                <th>Problema</th>
                                <th>Prioridade</th>
                                <th>Solicitante</th>
                                <th>Atendente</th>
                                <th>Abertura</th>
                                <th>Quant. Arquivos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($andamento as $values) {
                                ?>
                                <tr style="background-color: <?= $prioridades[$values['prioridade']] ?>" solicitacao="<?= $values['solicitacao']; ?>">
                                    <td>
                                        <?= $values['projeto'] ?>
                                    </td>
                                    <td>
                                        <?= $values['problema'] ?>
                                    </td>
                                    <td>
                                        <?= $values['prioridade'] ?>
                                    </td>
                                    <td>
                                        <?= $values['solicitante'] ?>
                                    </td>
                                    <td>
                                        <?= $values['atendente'] ?>
                                    </td>
                                    <td>
                                        <?= $values['abertura'] ?>
                                    </td>
                                    <td>
                                        <?= $values['arquivos'] ?>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>