

<script type="text/javascript">
    $(document).ready(function () {

        $('tbody > tr').click(function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/visualizar" ?>/' + $(this).attr('solicitacao'));
        });

        $('#accordion').accordion({
            collapsible: true
        });

    });
</script>


<div class="container">

    <div id="accordion">
        <h3>
            Solicitações em aberto
        </h3>
        <div>

            <table class="table-solicitacoes u-full-width">
                <thead>
                    <tr>
                        <th class="col3 text-center">Projeto</th>
                        <th class="col2 text-center">Problema</th>
                        <th class="col1 text-center">Prioridade</th>
                        <th class="text-center">Solicitante</th>
                        <th class="text-center">Atendente</th>
                        <th class="text-center">Abertura</th>
                        <th class="text-center">Q. Arquivos</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($aberta as $values) {
                        ?>
                        <tr style="background-color: <?= $prioridades[$values['prioridade']] ?>" solicitacao="<?= $values['solicitacao']; ?>">
                            <td>
                                <?= $values['projeto'] ?>
                            </td>
                            <td>
                                <?= $values['problema'] ?>
                            </td>
                            <td>
                                <?= $values['prioridade'] ?>
                            </td>
                            <td>
                                <?= $values['solicitante'] ?>
                            </td>
                            <td>
                                <?= $values['atendente'] ?>
                            </td>
                            <td>
                                <?= $values['abertura'] ?>
                            </td>
                            <td>
                                <?= $values['arquivos'] ?>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>

        </div>

        <h3>
            Solicitações em atendimento
        </h3>
        <div>

            <table class="table-solicitacoes u-full-width">
                <thead>
                    <tr>
                        <th class="col3 text-center">Projeto</th>
                        <th class="col2 text-center">Problema</th>
                        <th class="col1 text-center">Prioridade</th>
                        <th class="text-center">Solicitante</th>
                        <th class="text-center">Atendente</th>
                        <th class="text-center">Abertura</th>
                        <th class="text-center">Q. Arquivos</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($andamento as $values) {
                        ?>
                        <tr style="background-color: <?= $prioridades[$values['prioridade']] ?>" solicitacao="<?= $values['solicitacao']; ?>">
                            <td>
                                <?= $values['projeto'] ?>
                            </td>
                            <td>
                                <?= $values['problema'] ?>
                            </td>
                            <td>
                                <?= $values['prioridade'] ?>
                            </td>
                            <td>
                                <?= $values['solicitante'] ?>
                            </td>
                            <td>
                                <?= $values['atendente'] ?>
                            </td>
                            <td>
                                <?= $values['abertura'] ?>
                            </td>
                            <td>
                                <?= $values['arquivos'] ?>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>

        </div>

    </div>

</div>