

<script type="text/javascript" src="<?= HTTP_JS . '/jquery.mask.min.js' ?>"></script>


<script type="text/javascript">

    /*
     * Instancia objeto para exiber mensagem de aguarde.
     */
    var aguarde = new Aguarde('<?= HTTP_IMG . '/change.gif' ?>');

    var Empresas = function () {

        var formulario = ''; // cadastrar ou alterar
        var empresa = 0;

        /**
         * Seta formulario para cadastro
         */
        this.setCadastrar = function () {
            formulario = 'cadastrar';
        };

        /**
         * Seta formulario de alteração
         */
        this.setAlterar = function () {
            formulario = 'alterar';
        };

        /**
         * Seta dados para solicitar posterior exclusão
         * @param {int} id_empresa Código do feedback
         */
        this.setExcluir = function (id_empresa) {
            empresa = id_empresa;
        };

        /**
         * Envia formulario para cadastro ou alteração
         */
        this.submitFormulario = function () {
            aguarde.mostrar();

            $.ajax({
                url: '<?= HTTP . '/Empresas/' ?>' + formulario,
                data: $('form[name=formulario]').serialize(),
                dataType: 'JSON',
                type: 'POST',
                async: false,
                success: function (data) {

                    if (data.status) {
                        $('#msg-status').removeClass('hide alert-danger').addClass('alert-success');
                        $('#msg-status').html(data.msg);
                    } else {
                        $('#msg-status').removeClass('hide alert-success').addClass('alert-danger');
                        $('#msg-status').html(data.msg);
                    }

                    geraTabelaEmpresa(data.empresas);
                }
            });

            aguarde.ocultar();
        };

        /*
         * Gera tabela com as empresas cadastradas
         * @param {json} data Objeto json com os tipo de feedback
         */
        var geraTabelaEmpresa = function (data) {
            var table = '<table class="u-full-width">';
            table += '<thead>';
            table += '<tr>';
            table += '<th class="col3">Empresa</th>';
            table += '<th class="col3">Endereço</th>';
            table += '<th class="col2">Telefone Fixo</th>';
            table += '<th class="col2">Telefone Celular</th>';
            table += '<th class="col2"></th>';
            table += '</tr>';
            table += '</thead>';
            table += '<tbody>';

            $.each(data, function (key, value) {
                table += '<tr>';
                table += '<td>' + value.empresa + '</td>';
                table += '<td>' + value.endereco + '</td>';
                table += '<td>' + value.telefone_fixo + '</td>';
                table += '<td>' + value.telefone_celular + '</td>';
                table += '<td class="text-center">';
                table += '<button type="button" name="editar" empresa="' + value.id + '">Editar</button>';
                table += '<button type="button" name="excluir" empresa="' + value.id + '">Excluir</button>';
                table += '</td>';
                table += '</tr>';
            });

            table += '</tbody>';
            table += '</table>';

            $('#tabelaEmpresas').html(table);

            ButtonEditar();
            ButtonExcluir();
        };

        /*
         * Solicita a exclusão do projeto
         */
        this.excluir = function () {
            aguarde.mostrar();

            $.ajax({
                url: '<?= HTTP . '/Empresas/excluir' ?>',
                data: 'id=' + empresa,
                dataType: 'json',
                type: 'post',
                async: false,
                success: function (data) {

                    if (data.status) {
                        $('#msg-status').removeClass('hide alert-danger').addClass('alert-success');
                        $('#msg-status').html(data.msg);
                    } else {
                        $('#msg-status').removeClass('hide alert-success').addClass('alert-danger');
                        $('#msg-status').html(data.msg);
                    }

                    geraTabelaEmpresa(data.empresas);
                }
            });

            aguarde.ocultar();
        };
    };

    empresa = new Empresas();

    /*
     * Gera botão para edição de feedback
     */
    var ButtonEditar = function () {

        $('button[name=editar]').button({
            text: false,
            icons: {
                primary: 'ui-icon-pencil'
            }
        }).on('click', function () {
            aguarde.mostrar();

            empresa.setAlterar();

            var id = $(this).attr('empresa');

            $.ajax({
                url: '<?= HTTP . '/Empresas/getDadosEmpresa' ?>',
                data: 'empresa=' + id,
                dataType: 'json',
                type: 'post',
                async: false,
                success: function (data) {
                    $('#inputID').val(data.id);
                    $('#inputEmpresa').val(data.empresa);
                    $('#inputEndereco').val(data.endereco);
                    $('#inputTelefoneFixo').val(data.telefone_fixo);
                    $('#inputTelefoneCelular').val(data.telefone_celular);
                }
            });

            $('#dialogEmpresas').dialog('option', 'title', 'Alterar empresa');
            $('#dialogEmpresas + div.ui-dialog-buttonpane > div.ui-dialog-buttonset > button:first-child > span.ui-button-text').html('Alterar');
            $('#dialogEmpresas').dialog('open');

            aguarde.ocultar();
        });

    };

    /*
     * Cria botão de exclusão e adiciona evento ao clica-lo
     */
    var ButtonExcluir = function () {

        $('button[name=excluir]').button({
            text: false,
            icons: {
                primary: 'ui-icon-close'
            }
        }).on('click', function () {
            $('#alertaExclusao').dialog('open');
            empresa.setExcluir($(this).attr('empresa'));
        });

    };

    $(document).ready(function () {

        ButtonEditar();
        ButtonExcluir();

        /*
         * Gera botão de cadastrar usuário e ação de clica-lo
         */
        $('button[type=button][name=cadastrar]').button({
            icons: {
                primary: 'ui-icon-circle-plus'
            }
        }).on('click', function () {
            aguarde.mostrar();
            empresa.setCadastrar();

            $('#dialogEmpresas').dialog('option', 'title', 'Cadastrar empresa');
            $('#dialogEmpresas + div.ui-dialog-buttonpane > div.ui-dialog-buttonset > button:first-child > span.ui-button-text').html('Cadastrar');
            $('#dialogEmpresas').dialog('open');

            aguarde.ocultar();
        });

        /*
         * dialog solicitando confirmação para exclusão.
         */
        $('#alertaExclusao').dialog({
            autoOpen: false,
            modal: true,
            closeOnEscape: false,
            buttons: [
                {
                    text: 'Excluir',
                    icons: {
                        primary: 'ui-icon-trash'
                    },
                    click: function () {
                        empresa.excluir();
                        $(this).dialog('close');
                    }
                },
                {
                    text: 'Cancelar',
                    icons: {
                        primary: 'ui-icon-close'
                    },
                    click: function () {
                        $(this).dialog('close');
                    }
                }
            ]
        });

    });

</script>


<div class="container">

    <div class="row">
        <div id="msg-status" class="alert hide text-center"></div>
    </div>

    <div class="row">
        <button type="button" name="cadastrar" id="cadastrar">Cadastrar</button>
    </div>

    <div id="tabelaEmpresas">

        <table class="u-full-width">
            <thead>
                <tr>
                    <th class="col3">Nome</th>
                    <th class="col3">Endereço</th>
                    <th class="col2">Telefone Fixo</th>
                    <th class="col2">Telefone Celular</th>
                    <th class="col2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($empresas as $values) { ?>
                    <tr>
                        <td><?= $values['empresa'] ?></td>
                        <td><?= $values['endereco'] ?></td>
                        <td><?= $values['telefone_fixo'] ?></td>
                        <td><?= $values['telefone_celular'] ?></td>
                        <td class="text-center">
                            <button type="button" name="editar" empresa="<?= $values['id'] ?>">Editar</button>
                            <button type="button" name="excluir" empresa="<?= $values['id'] ?>">Excluir</button>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

    </div>

</div>

<div id="alertaExclusao" title="Alerta de remoção">
    <p class="ui-state-error-text">
        Deseja realmente remover esta empresa?
    </p>
</div>