

<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> text-center">
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <form class="form-horizontal" method="post" action="<?= $link ?>">
        <input type="hidden" name="inputID" id="inputID" value="0" />

        <div class="row" id="divEmpresa">
            <label for="inputEmpresa" class="two columns">Empresa</label>
            <input type="text" class="ten columns" id="inputEmpresa" required name="inputEmpresa" placeholder="Empresa">
        </div>

        <div class="row">
            <label for="inputEndereco" class="two columns">Endereço</label>
            <input type="text" class="ten columns" id="inputEndereco" name="inputEndereco" placeholder="Endereço">
        </div>

        <div class="row">
            <label for="inputTelefoneFixo" class="two columns">Telefone Fixo</label>
            <input type="text" class="ten columns" id="inputTelefoneFixo" name="inputTelefoneFixo" required placeholder="Telefone Fixo">
        </div>

        <div class="row">
            <label for="inputTelefoneCelular" class="two columns">Telefone Celular</label>
            <input type="text" class="ten columns" id="inputTelefoneCelular" name="inputTelefoneCelular" placeholder="Telefone Celular">
        </div>

        <div class="row">
            <button type="<?= $botao['type']; ?>" name="submit-dados">
                <?= $botao['value']; ?>
            </button>
        </div>
    </form>
</div>