

<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> alert-error text-center">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <form class="form-horizontal" method="post" action="<?= $link ?>">
        <input type="hidden" name="inputID" id="inputID" value="0" />
        <div class="form-group" id="divEmpresa">
            <label for="inputEmpresa" class="control-label col-xs-2">Empresa</label>
            <div class="col-xs-6">
                <input type="text" class="form-control" id="inputEmpresa" required name="inputEmpresa" placeholder="Empresa">
            </div>
        </div>

        <div class="form-group">
            <label for="inputEndereco" class="control-label col-xs-2">Endereço</label>
            <div class="col-xs-6" id="divEndereco">
                <input type="text" class="form-control" id="inputEndereco" name="inputEndereco" placeholder="Endereço">
            </div>
        </div>

        <div class="form-group">
            <label for="inputTelefoneFixo" class="control-label col-xs-2">Telefone Fixo</label>
            <div class="col-xs-6" id="divTelefoneFixo">
                <input type="text" class="form-control" id="inputTelefoneFixo" name="inputTelefoneFixo" required placeholder="Telefone Fixo">
            </div>
        </div>

        <div class="form-group">
            <label for="inputTelefoneCelular" class="control-label col-xs-2">Telefone Celular</label>
            <div class="col-xs-6" id="divTelefoneCelular">
                <input type="text" class="form-control" id="inputTelefoneCelular" name="inputTelefoneCelular" placeholder="Telefone Celular">
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <button type="<?= $botao['type']; ?>" name="submit-dados" class="btn btn-default">
                    <?= $botao['value']; ?>
                </button>
            </div>
        </div>
    </form>
</div>