

<script type="text/javascript">
    $(document).ready(function () {

        /*
         * Dados em formato json
         */
        var participantes = <?= $participantes ?>;
        var solicitacao = <?= $solicitacao ?>;

        /*
         * Gera caixa se seleção de solicitantes e técnicos
         */
        $("select[name='selectSolicitante'] > option").remove();
        $("select[name='selectTecnico'] > option").remove();
        $("select[name='selectSolicitante']").append('<option value="0" disabled selected>Solicitante</option>');
        $("select[name='selectTecnico']").append('<option value="0" disabled selected>Técnico</option>');

        $.each(participantes, function (key, value) {
            $("select[name='selectSolicitante']").append('<option value="' + value.id + '">' + value.nome + '</option>');

            if (value.tecnico) {
                $("select[name='selectTecnico']").append('<option value="' + value.id + '">' + value.nome + '</option>');
            }
        });

        /*
         * Preenche campos com dados da solicitação.
         */
        $("input[name='inputID']").val(solicitacao.solicitacao);
        $("input[name='solicitacaoOrigem']").val(solicitacao.solicitacao_origem);
        $("select[name='selectProjeto']").val(solicitacao.projeto_problema);
        $("select[name='selectPrioridade']").val(solicitacao.prioridade);
        $("select[name='selectSolicitante']").val(solicitacao.solicitante);
        $("select[name='selectTecnico']").val(solicitacao.tecnico);
        $("textarea[name='textareaDescricao']").val(solicitacao.descricao);

        /*
         * Monta tabela com relação dos arquivos anexos
         */

        if (solicitacao.arquivos.length > 0) {
            $('#arquivos-antigos').addClass('well well-sm');

            var table = '<table class="table" id="table-arquivos">' +
                    '<thead><tr><th colspan="2" class="text-center">Arquivos anexos na solicitação</th></tr></thead>' +
                    '<tbody></tbody>' +
                    '</table>';

            $('#arquivos-antigos').html(table);

            var table = '';

            $.each(solicitacao.arquivos, function (key, value) {
                table += '<tr id="arquivos' + value.id + '"><td>' + value.nome + '</td>' +
                        '<td><button class="btn btn-danger" data-id="' + value.id + '" type="button">Excluir</button></td></tr>';
            });

            $('#table-arquivos > tbody').html(table);
        }

        /*
         * Implementa operações referentes a remoção de anexos
         */

        $('td > button[type=button]').on('click', function () {
            $("input[type='hidden'][name='id_arquivo']").val($(this).attr('data-id'));
            delete_file.dialog('open');
        });

        /*
         * Dialog de confirmação antes da remoção do anexo.
         */

        var delete_file = $('#confirm-delete-file').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "Remover": function () {

                    $.ajax({
                        url: "<?= HTTP . '/Solicitacao/removerArquivo' ?>",
                        data: 'id=' + $("input[type='hidden'][name='id_arquivo']").val() +
                                '&projeto_tipo_problema=' + $("select[name='selectProjeto']").val(),
                        type: 'POST',
                        dataType: 'json',
                        success: function (data) {
                            $("#status").prop('title', 'Atenção');
                            $("#msg-status").html(data.status ? "Arquivo removido com sucesso." : "Falha ao remover arquivo. Caso persista o erro contate administrador.");

                            status_msg.dialog("open");

                            if (data.status) {
                                var id = $("input[type='hidden'][name='id_arquivo']").val();
                                $("#arquivos" + id).remove();

                                if ($("#table-arquivos > tbody > tr").length == 0) {
                                    $("#arquivos-antigos").hide();
                                }
                            }
                        }
                    });

                    delete_file.dialog('close');
                },
                "Cancelar": function () {
                    delete_file.dialog('close');
                }
            }
        });

        /*
         * Monta dialog para exibição de mensagens de aviso.
         */

        var status_msg = $('#status').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "OK": function () {
                    status_msg.dialog("close");
                }
            }
        });

    });
</script>

<input type="hidden" name="id_arquivo" />

<div id="confirm-delete-file" title="Atenção">
    <p>Deseja excluir este arquivo?</p>
</div>

<div id="status" title="Atenção">
    <p id="msg-status"></p>
</div>