

<script type="text/javascript">
    $(document).ready(function () {

        $('tbody > tr').click(function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/visualizar" ?>/' + $(this).attr('solicitacao'));
        });

    });
</script>


<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div
            class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> alert-error text-center">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <div>
        <table class="table table-responsive table-bordered table-solicitacoes">
            <thead>
                <tr>
                    <th>Projeto</th>
                    <th>Problema</th>
                    <th>Prioridade</th>
                    <th>Solicitante</th>
                    <th>Atendente</th>
                    <th>Abertura</th>
                    <th>Quant. Arquivos</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($solicitacoes as $values) {
                    ?>
                    <tr style="background-color: <?= $prioridades[$values['prioridade']] ?>" solicitacao="<?= $values['solicitacao']; ?>">
                        <td>
                            <?= $values['projeto'] ?>
                        </td>
                        <td>
                            <?= $values['problema'] ?>
                        </td>
                        <td>
                            <?= $values['prioridade'] ?>
                        </td>
                        <td>
                            <?= $values['solicitante'] ?>
                        </td>
                        <td>
                            <?= $values['atendente'] ?>
                        </td>
                        <td>
                            <?= $values['abertura'] ?>
                        </td>
                        <td>
                            <?= $values['arquivos'] ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>