
<script type="text/javascript">

    $(document).ready(function () {

        var excluir_solicitacao = $('#excluir-solicitacao').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "Excluir": function () {
                    $(location).attr('href', '<?= HTTP . "/Solicitacao/excluir/{$id_solicitacao}" ?>');
                    excluir_solicitacao.dialog('close');
                },
                "Cancelar": function () {
                    excluir_solicitacao.dialog('close');
                }
            }
        });

        var redirecionar_solicitacao = $('#redirecionar-solicitacao').dialog({
            autoOpen: false,
            modal: true,
            width: 450,
            buttons: {
                "Redirecionar": function () {
                    var tecnico = $('select[name=selectTecnico]').val();
                    $(location).attr('href', '<?= HTTP . "/Solicitacao/redirecionar/{$id_solicitacao}" ?>/' + tecnico);
                    redirecionar_solicitacao.dialog('close');
                },
                "Cancelar": function () {
                    redirecionar_solicitacao.dialog('close');
                }
            }
        });

        $('#editar').on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/editar/{$id_solicitacao}" ?>');
        });
        $('#atender').on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/atender/{$id_solicitacao}" ?>');
        });
        $('#sub-chamado').on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/subChamado/{$id_solicitacao}" ?>');
        });
        $('#excluir').on('click', function () {
            excluir_solicitacao.dialog('open');
        });
        $('#redirecionar').on('click', function () {
            redirecionar_solicitacao.dialog('open');
        });
        $('#feedback').on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/feedback/{$id_solicitacao}" ?>');
        });
        $('#encerrar').on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/encerrar/{$id_solicitacao}" ?>');
        });
    });

</script>

<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div
            class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> alert-error text-center">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <div class="form-group">
        <div class="ui-widget-header ui-corner-all">
            <button class="btn btn-default <?= ($editar) ? '' : 'disabled' ?>" id="editar">
                <span class="glyphicon glyphicon-pencil text-info"></span> Editar
            </button>
            <button class="btn btn-default <?= ($atender) ? '' : 'disabled' ?>" id="atender">
                <span class="glyphicon glyphicon-wrench text-info"></span> Atender
            </button>
            <button class="btn btn-default <?= ($sub_chamado) ? '' : 'disabled' ?>" id="sub-chamado">
                <span class="glyphicon glyphicon-plus-sign text-info"></span> Sub-Chamado
            </button>
            <button class="btn btn-default <?= ($excluir) ? '' : 'disabled' ?>" id="excluir">
                <span class="glyphicon glyphicon-remove text-danger"></span> Excluir
            </button>
            <button class="btn btn-default <?= ($redirecionar) ? '' : 'disabled' ?>" id="redirecionar">
                <span class="glyphicon glyphicon-transfer text-primary"></span> Redirecionar
            </button>
            <button class="btn btn-default <?= ($feedback) ? '' : 'disabled' ?>" id="feedback">
                <span class="glyphicon glyphicon-comment text-primary"></span> Feedback
            </button>
            <button class="btn btn-default <?= ($encerrar) ? '' : 'disabled' ?>" id="encerrar">
                <span class="glyphicon glyphicon-ok text-success"></span> Encerrar
            </button>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Projeto:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['projeto'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Problema:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['problema'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Prioridade:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['prioridade'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Solicitante:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['solicitante'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Atendente:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['atendente'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Técnico:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['tecnico'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Abertura:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['abertura'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Atendimento:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['atendimento'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Encerramento:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['encerramento'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <label class="panel-title">Descrição:</label>
                </div>
                <div class="panel-body">
                    <?= $solicitacao['descricao'] ?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <label class="panel-title">Arquivos anexos:</label>
                </div>
                <div class="panel-body text-center">
                    <?php
                    if (empty($solicitacao['arquivos'])) {
                        echo "Esta solicitação não contém nenhum arquivo em anexo.";
                    } else {
                        foreach ($solicitacao['arquivos'] as $values) {
                            echo "<a href=" . HTTP . "/Solicitacao/downloadArquivo/{$values['id']} /> {$values['nome']}</a><br>";
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>

</div>

<div id="excluir-solicitacao" title="Atenção">
    <p>Deseja excluir está solicitação?</p>
</div>

<div id="redirecionar-solicitacao" title="Redirecionamento de chamado a outro técnico.">
    <div class="col-xs-12">
        <div class="form-group">
            <label class="control-label col-xs-4">
                Técnico:
            </label>
            <div class="col-xs-8">
                <select name="selectTecnico" id="selectTecnico" class="form-control">
                    <option value=""></option>
                    <?php
                    foreach ($tecnicos as $values) {
                        if ($values['tecnico'] == 1) {
                            ?>
                            <option value="<?= $values['id'] ?>"><?= $values['nome']; ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
</div>