
<script type="text/javascript" src="<?= HTTP_JS . '/tinymce/tinymce.min.js' ?>"></script>

<script type="text/javascript">

    tinymce.init({
        selector: '#textareaDescricao',
        language: 'pt_BR',
    });

    tinymce.init({
        selector: '#respostaFeedback',
        language: 'pt_BR',
    });

    $(document).ready(function () {

        var excluir_solicitacao = $('#excluir-solicitacao').dialog({
            autoOpen: false,
            modal: true,
            buttons: {
                "Excluir": function () {
                    $(location).attr('href', '<?= HTTP . "/Solicitacao/excluir/{$id_solicitacao}" ?>');
                    excluir_solicitacao.dialog('close');
                },
                "Cancelar": function () {
                    excluir_solicitacao.dialog('close');
                }
            }
        });

        var redirecionar_solicitacao = $('#redirecionar-solicitacao').dialog({
            autoOpen: false,
            modal: true,
            width: 450,
            buttons: {
                "Redirecionar": function () {
                    var tecnico = $('select[name=selectTecnico]').val();
                    $(location).attr('href', '<?= HTTP . "/Solicitacao/redirecionar/{$id_solicitacao}" ?>/' + tecnico);
                    redirecionar_solicitacao.dialog('close');
                },
                "Cancelar": function () {
                    redirecionar_solicitacao.dialog('close');
                }
            }
        });

        var feedback_solicitacao = $('#feedback-solicitacao').dialog({
            autoOpen: false,
            modal: true,
            width: 850,
            buttons: {
                "Criar Feedback": function () {
                    feedback_solicitacao.dialog('close');
                    $('form[name=solicitar-feedback]').submit();
                },
                "Cancelar": function () {
                    feedback_solicitacao.dialog('close');
                }
            }
        });

        var responder_feedback = $('#responderFeedback').dialog({
            autoOpen: false,
            modal: true,
            width: 850,
            buttons: {
                "Responder Feedback": function () {
                    responder_feedback.dialog('close');
                },
                "Cancelar": function () {
                    responder_feedback.dialog('close');
                }
            }
        });

        $("button[class=feedback-aberto]").button().on('click', function () {
            $("input[type=hidden][name=feedback_id]").val($(this).attr("feedback"));
            responder_feedback.dialog('open');
        });
        $("button[class=feedback-atendida]").button();

        $('#editar').button({
            icons: {
                primary: 'ui-icon-pencil'
            }
        }).on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/editar/{$id_solicitacao}" ?>');
        });

        $('#atender').button({
            icons: {
                primary: 'ui-icon-wrench'
            }
        }).on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/atender/{$id_solicitacao}" ?>');
        });

        $('#sub-chamado').button({
            icons: {
                primary: 'ui-icon-circle-plus'
            }
        }).on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/subChamado/{$id_solicitacao}" ?>');
        });

        $('#excluir').button({
            icons: {
                primary: 'ui-icon-closethick'
            }
        }).on('click', function () {
            excluir_solicitacao.dialog('open');
        });

        $('#redirecionar').button({
            icons: {
                primary: 'ui-icon-transferthick-e-w'
            }
        }).on('click', function () {
            redirecionar_solicitacao.dialog('open');
        });

        $('#feedback').button({
            icons: {
                primary: 'ui-icon-comment'
            }
        }).on('click', function () {
            feedback_solicitacao.dialog('open');
        });

        $('#encerrar').button({
            icons: {
                primary: 'ui-icon-check'
            }
        }).on('click', function () {
            $(location).attr('href', '<?= HTTP . "/Solicitacao/encerrar/{$id_solicitacao}" ?>');
        });
    });

</script>

<div class="container">

    <?php
    if ((!empty($_SESSION ['msg_erro'])) || (!empty($_SESSION ['msg_sucesso']))) {
        ?>
        <div
            class="alert <?= empty($_SESSION['msg_erro']) ? 'alert-success' : 'alert-danger'; ?> alert-error text-center">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <?= empty($_SESSION['msg_erro']) ? $_SESSION['msg_sucesso'] : $_SESSION['msg_erro']; ?>
        </div>
        <?php
        unset($_SESSION ['msg_erro']);
        unset($_SESSION ['msg_sucesso']);
    }
    ?>

    <div class="form-group">
        <div class="ui-widget-header ui-corner-all">
            <button class="ui-button-warning" <?= ($editar) ? '' : 'disabled' ?> id="editar">
                Editar
            </button>
            <button <?= ($atender) ? '' : 'disabled' ?> id="atender">
                Atender
            </button>
            <button <?= ($sub_chamado) ? '' : 'disabled' ?> id="sub-chamado">
                Sub-Chamado
            </button>
            <button <?= ($excluir) ? '' : 'disabled' ?> id="excluir">
                Excluir
            </button>
            <button <?= ($redirecionar) ? '' : 'disabled' ?> id="redirecionar">
                Redirecionar
            </button>
            <button <?= ($feedback) ? '' : 'disabled' ?> id="feedback">
                Feedback
            </button>
            <button <?= ($encerrar) ? '' : 'disabled' ?> id="encerrar">
                Encerrar
            </button>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Projeto:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['projeto'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Problema:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['problema'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Prioridade:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['prioridade'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Solicitante:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['solicitante'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Atendente:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['atendente'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Técnico:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['tecnico'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Abertura:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['abertura'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Atendimento:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['atendimento'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <label class="control-label col-xs-4">
                        Encerramento:
                    </label>
                    <div class="col-xs-8">
                        <input type="text" value="<?= $solicitacao['encerramento'] ?>" disabled class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <label class="panel-title">Feedback</label>
                </div>
                <div class="panel-body text-center">
                    <table class="table">
                        <thead>
                            <tr>
                                <th rowspan="2" class="col-xs-2">Pergunta</th>
                                <th rowspan="2" class="col-xs-2">Resposta</th>
                                <th colspan="2" class="col-xs-4">Data feedback</th>
                                <th rowspan="2" class="col-xs-4">Responsável pelo feedback</th>
                            </tr>
                            <tr>
                                <th class="col-xs-2">
                                    Pegunta
                                </th>
                                <th class="col-xs-2">
                                    Resposta
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($feedback_solicitado as $values) {
                                ?>
                                <tr class="<?= $values['aberta'] ? 'warning' : 'success'; ?>">
                                    <td><?= $values['pergunta'] ?></td>
                                    <td><?= $values['resposta'] ?></td>
                                    <td><?= $values['inicio'] ?></td>
                                    <td><?= $values['fim'] ?></td>
                                    <td class="row">
                                        <div class="col-xs-6">
                                            <?php echo $values['nome_responsavel']; ?>
                                        </div>
                                        <div class="col-xs-6 text-center" style="float: right;">
                                            <?php
                                            if ($values['aberta'] && $values['responsavel'] === $_SESSION['id']) {
                                                ?>
                                                <button type="button" class="feedback-aberto" feedback="<?= $values['id'] ?>">
                                                    Responder
                                                </button>
                                                <?php
                                            } else {
                                                ?>
                                                <button type="button" class="feedback-atendida" feedback="<?= $values['id'] ?>">
                                                    Visualizar
                                                </button>
                                                <?php
                                            }
                                            ?>
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <label class="panel-title">Descrição:</label>
                </div>
                <div class="panel-body">
                    <?= $solicitacao['descricao'] ?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <label class="panel-title">Arquivos anexos:</label>
                </div>
                <div class="panel-body text-center">
                    <?php
                    if (empty($solicitacao['arquivos'])) {
                        echo "Esta solicitação não contém nenhum arquivo em anexo.";
                    } else {
                        foreach ($solicitacao['arquivos'] as $values) {
                            echo "<a href=" . HTTP . "/Solicitacao/downloadArquivo/{$values['id']} /> {$values['nome']}</a><br>";
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>

</div>

<div id="excluir-solicitacao" title="Atenção">
    <p>Deseja excluir está solicitação?</p>
</div>

<div id="redirecionar-solicitacao" title="Redirecionamento de chamado a outro técnico.">
    <div class="col-xs-12">
        <div class="form-group">
            <label class="control-label col-xs-4">
                Técnico:
            </label>
            <div class="col-xs-8">
                <select name="selectTecnico" id="selectTecnico" class="form-control">
                    <option value=""></option>
                    <?php
                    foreach ($tecnicos as $values) {
                        if ($values['tecnico'] == 1) {
                            ?>
                            <option value="<?= $values['id'] ?>"><?= $values['nome']; ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
</div>

<div id="feedback-solicitacao" title="Solicitação de feedback">
    <form action="<?= HTTP . "/Solicitacao/feedback" ?>" name="solicitar-feedback" method="POST">
        <input type="hidden" name="solicitacao" value="<?= "{$id_solicitacao}" ?>" />
        <div class="form-group">
            <div class="col-xs-12">
                <label class="control-label col-xs-4">Tipo de feedback:</label>
                <div class="col-xs-8">
                    <select name="selectFeedback" id="selectFeedback" class="form-control">
                        <option value=""></option>
                        <?php
                        foreach ($tipos_feedback AS $values) {
                            ?>
                            <option value="<?= $values['id'] ?>">
                                <?= $values['nome'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label class="control-label col-xs-4">Destinátario:</label>
                <div class="col-xs-8">
                    <select name="selectDestinatario" id="selectDestinatario" class="form-control">
                        <option value=""></option>
                        <?php
                        foreach ($tecnicos as $values) {
                            ?>
                            <option value="<?= $values['id'] ?>"><?= $values['nome']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="textareaDescricao" class="col-xs-12">Descrição:</label>
            <div class="col-xs-12 form-group">
                <textarea name="textareaDescricao" id="textareaDescricao"></textarea>
            </div>
        </div>
    </form>
</div>

<div id="responderFeedback">
    <form method="post" name="respostaFeedback">
        <input type="hidden" name="feedback_id" id="feedback_id" />
        <div class="form-group">
            <label for="respostaFeedback" class="col-xs-12">Resposta:</label>
            <div class="col-xs-12 form-group">
                <textarea name="respostaFeedback" id="respostaFeedback"></textarea>
            </div>
        </div>
    </form>
</div>