

<script type="text/javascript">
	$(document).ready(function(){

		var array = [<?= implode(',', $feriados) ?>];
		
		$("#calendario").datepicker({
            numberOfMonths: 12,
            buttonImageOnly: true,
            dateFormat: 'yy-mm-dd',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            nextText: 'Próximo',
            prevText: 'Anterior',
            numberOfMonths: [ 3, 4 ],
            onSelect: function(date, inst){
				if($("#mostrar-feriados").attr('disabled')){
					$("#opcao-feriados-dialog").modal({
						backdrop: 'static',
						keyboard: false
					});
				} else {
					$("#feriados-dialog").modal({
						backdrop: 'static',
						keyboard: false
					});
				}

				$("input[name='data-feriado']").val(date);
            },
            beforeShowDay: function (date) {
                var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                return [array.indexOf(string) <?= $calendario ? '==' : '!='; ?> -1]
            }
		});
		
	});
</script>