
<script type="text/javascript">
	$(function(){
		$.fn.mostrarFeriado = function(){
			$.ajax({
				url: '<?= HTTP . '/Horarios/mostrarFeriados'; ?>',
				type: 'POST',
				success: function(html){
					$("#calendario").empty();
					$("#calendario").html(html);
				}
			});
		}
	
		$.fn.mostrarCalendario = function(){
			$.ajax({
				url: '<?= HTTP . '/Horarios/mostrarCalendario'; ?>',
				type: 'POST',
				success: function(html){
					$("#calendario").empty();
					$("#calendario").html(html);
				}
			});
		}
	});
</script>

<script type="text/javascript">
	$(document).ready(function(){

		$('#alterar').on('click', function(){
			$("#opcao-feriados-dialog").modal('hide');

			$.ajax({
				url: '<?= HTTP . '/Horarios/getFeriadoByDia' ?>',
				type: 'POST',
				data: 'dia=' + $('#data-feriado').val(),
				dataType: 'json',
				success: function (json){
					$('#inputNome').val(json.nome);
					$('#inputDataFixa').attr('disabled', true);
					$("#feriados-dialog").modal({
						backdrop: 'static',
						keyboard: false
					});
				}
			});
		});

		$('#excluir').on('click', function(){
			$("#opcao-feriados-dialog").modal('hide');

			$.ajax({
				url: '<?= HTTP . '/Horarios/deleteFeriado' ?>',
				type: 'POST',
				data: 'data=' + $('#data-feriado').val(),
				success: function(){
					if($("#mostrar-feriados").attr('disabled')){
						$("#mostrar-feriados").click();
					} else {
						$("#mostrar-calendario").click();
					}
				}
			});
		});
		
		$('#confirmar').on('click', function(){
			var url = '<?= HTTP ?>' + ($("#mostrar-feriados").attr('disabled') ? '/Horarios/alteraFeriados' : '/Horarios/cadastraFeriados');
			$.ajax({
				url: url,
				type: 'POST',
				data: 'data=' + $('#data-feriado').val() + '&nome=' + $('#inputNome').val() +
				'&replicar=' + $('#inputDataFixa:checked').length,
				success: function(html){
					if($("#mostrar-feriados").attr('disabled')){
						$('#inputDataFixa').attr('disabled', false);
						$("#mostrar-feriados").click();
					} else {
						$("#mostrar-calendario").click();
					}
					$("#feriados-dialog").modal('hide');
					$('#inputNome').val('');
					$('#inputDataFixa:checked').attr('checked', false);
				}
			});
		});

		$("#mostrar-feriados").on('click', function(){
			$("#calendario").datepicker("destroy");
			$(this).attr("disabled", true);
			$("#mostrar-calendario"). attr("disabled", false);
			$().mostrarFeriado();
		});

		$("#mostrar-calendario").on('click', function(){
			$("#calendario").datepicker("destroy");
			$(this).attr("disabled", true);
			$("#mostrar-feriados"). attr("disabled", false);
			$().mostrarCalendario();
		});

		$("#mostrar-calendario").click();

	});
</script>

<style type="text/css">
div #calendario>div {
	margin: auto !important;
	width: 90% !important;
}

.botoes-mostrar {
	width: 100%;
	text-align: center;
	margin: 10px auto;
}
</style>

<div class="container">

	<div class="well">
		<div class="botoes-mostrar";>
			<button id="mostrar-feriados" type="button" class="btn btn-primary">
				Mostrar Feriados</button>
			<button id="mostrar-calendario" type="button" class="btn btn-primary">
				Mostrar Calendário</button>
		</div>

		<div id="calendario"></div>
	</div>

	<div id="feriados-dialog" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center">Feriados</h4>
				</div>

				<div class="modal-body">

					<div class="form-horizontal">

						<input type="hidden" name="data-feriado" id="data-feriado" />

						<div class="form-group">
							<label for="inputNome" class="control-label col-xs-4">Nome do
								feriado</label>
							<div class="col-xs-8">
								<input type="text" class="form-control" id="inputNome" required
									name="inputNome" placeholder="Nome do feriado" maxlength="50">
							</div>
						</div>

						<div class="form-group">
							<div class="checkbox col-xs-12">
								<label for="inputDataFixa"> <input type="checkbox"
									name="inputDataFixa" id="inputDataFixa" /> Data fixa (este
									feriado será replicado nos anos seguintes)
								</label>
							</div>
						</div>

					</div>

				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-success" id="confirmar">Adicionar</button>
				</div>
			</div>
		</div>
	</div>

	<div id="opcao-feriados-dialog" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center">Feriados</h4>
				</div>

				<div class="modal-body">
					<p>
						Qual operação deseja realizar?
					</p>				
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">
						Cancelar
					</button>
					<button type="button" class="btn btn-default" id="alterar">
						<span class="glyphicon glyphicon-pencil text-primary"></span> - Alterar
					</button>
					<button type="button" class="btn btn-default" id="excluir">
						<span class="glyphicon glyphicon-remove text-danger"></span> - Excluir
					</button>
				</div>
			</div>
		</div>
	</div>
	
</div>