
<script type="text/javascript">
	$(document).ready(function(){

		$(function(){
			$.fn.dialogFeriados = function (values){
        		$("#feriados-dialog").modal({
        			backdrop: 'static',
                    keyboard: false
        		});

				$("input[name='data-feriado']").val(values.date);

        		return false;
			};
		});

		$("#mostrar-feriados").on('click', function(){
			$("form[name='form-cadastro']").attr("action", '<?= HTTP . '/Horarios/alterarFeriados'; ?>');
			$("#calendario").datepicker("destroy");
			$(this).attr("disabled", true);
			$("#mostrar-calendario"). attr("disabled", false);
		});

		$("#mostrar-calendario").on('click', function(){
			$("form[name='form-cadastro']").attr("action", '<?= HTTP . '/Horarios/cadastrarFeriados'; ?>');
			$("#calendario").datepicker("destroy");
			$(this).attr("disabled", true);
			$("#mostrar-feriados"). attr("disabled", false);

			$.ajax({
				url: '<?= HTTP . '/Horarios/mostrarCalendario'; ?>',
				type: 'POST',
				success: function(html){
					$("#calendario").empty();
					$("#calendario").html(html);
				}
			});
			
		});

		$("#mostrar-calendario").click();

	});
</script>

<style type="text/css">
div #calendario>div {
	margin: auto !important;
	width: 90% !important;
}

.botoes-mostrar {
	width: 100%;
	text-align: center;
	margin: 10px auto;
}
</style>

<div class="container">

	<div class="well">
		<div class="botoes-mostrar";>
			<button id="mostrar-feriados" type="button" class="btn btn-primary">
				Mostrar Feriados</button>
			<button id="mostrar-calendario" type="button" class="btn btn-primary">
				Mostrar Calendário</button>
		</div>

		<div id="calendario"></div>
	</div>

	<form method="POST" name="form-cadastro"
		action="<?= HTTP . '/Horarios/cadastrarFeriados'; ?>"
		id="feriados-dialog" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">&times;</button>
					<h4 class="modal-title text-center">Feriados</h4>
				</div>

				<div class="modal-body">

					<div class="form-horizontal">

						<input type="hidden" name="data-feriado" />

						<div class="form-group">
							<label for="inputDescricao" class="control-label col-xs-2">Descrição</label>
							<div class="col-xs-10">
								<input type="text" class="form-control" id="inputDescricao"
									required name="inputDescricao" placeholder="Descrição">
							</div>
						</div>

						<div class="form-group">
							<div class="checkbox col-xs-12">
								<label for="inputDataFixa"> <input type="checkbox"
									name="inputDataFixa" id="inputDataFixa" value="fixa" /> Data
									fixa (este feriado será replicado nos anos seguintes)
								</label>
							</div>
						</div>

					</div>

				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-success" id="confirma">Adicionar</button>
				</div>
			</div>
		</div>
	</form>

</div>